version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    ports:
      - '27017-27019:27017-27019'
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: 'redis'
    container_name: 'redis'
    ports:
      - "6379:6379"
