version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo-container'
    ports:
      - '27017-27019:27017-27019'
  mq:
    image: 'rabbitmq:management'
    container_name: 'rabbitmq-container'
    ports:
      - "5672:5672"
      - "15672:15672"
