server:
  port: 8080
logging:
  level:
    app: trace
    org:
      springframework:
        cloud:
          netflix:
            zuul: trace
spring:
  mvc:
    log-request-details: true
zuul:
  sensitive-headers: Authorization, Cookie, Set-Cookie
  routes:
    auth:
      path: /auth/**
      service-id: auth
    tickets:
      path: /tickets/**
      service-id: tickets
  trace-request-body: true
  include-debug-header: true

