server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/api/**]':
            allowed-headers: "*"
            allowed-origins: "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
        add-to-simple-url-handler-mapping: true
