server:
  port: 8080
logging:
  level:
    app: trace
    org:
      springframework:
        cloud:
          netflix:
            zuul: trace
spring:
  mvc:
    log-request-details: true
    log-resolved-exception: true
zuul:
  sensitive-headers: Authorization, Cookie, Set-Cookie
  routes:
    auth:
      path: /api/users/**
      service-id: auth
    tickets:
      path: /api/tickets/**
      service-id: tickets
    orders:
      path: /api/orders/**
      service-id: orders
    payments:
      path: /api/payments/**
      service-id: payments
    client:
      path: /**
      url: http://localhost:3000
  trace-request-body: true
  include-debug-header: true

